-- ============================================================
-- PopPilot — Utilisateurs : liaison Supabase Auth <-> table utilisateur
-- ============================================================
-- ⚠️ NE PLUS EXÉCUTER CE FICHIER À LA MAIN. Il est conservé comme référence
-- de la correspondance en vigueur ; la liaison se fait par :
--
--     python api/lier_utilisateurs.py
--
-- POURQUOI : les UUID de auth.users changent dès qu'un compte est supprimé puis
-- recréé dans Authentication > Users. Les coller ici les figerait et la liaison
-- casserait silencieusement (l'utilisateur obtiendrait un 401 sans explication).
-- Le script relit les UUID dans auth.users à chaque exécution : il est idempotent
-- et se répare tout seul.
--
-- Pour ajouter/retirer quelqu'un : modifier le dictionnaire CORRESPONDANCE en tête
-- de api/lier_utilisateurs.py, puis relancer le script.
--
-- Correspondance en vigueur (comptes créés dans Authentication > Users) :
--
--   daf@poppilot.com         -> daf         DIRECTION  toutes agences   (+ import)
--   cdg@poppilot.com         -> cdg         CDG        toutes agences   (+ import)
--   bmvictoire@poppilot.com  -> bmvictoire  AGENCE     AGENCE DE VICTOIRE
--   audit@poppilot.com       -> audit       AUDIT      toutes agences   (lecture)
--
-- Rôles valides (api/socle/auth.py) : DIRECTION, CDG, AGENCE, AUDIT.
--   - DIRECTION / CDG / AUDIT : voient toutes les agences (pp_acces_total).
--   - AGENCE : cloisonné à la valeur de la colonne `agence`, qui doit correspondre
--     EXACTEMENT au libellé du registre api/socle/agences.py (ex. 'AGENCE DE VICTOIRE').
--   - Écriture (import, calculs) réservée à DIRECTION / CDG.
--
-- mot_de_passe_hash / sel restent NOT NULL dans le schéma mais ne servent plus :
-- l'authentification est entièrement déléguée à Supabase Auth.
--
-- Contrôle après liaison :  python api/verifier_supabase.py
-- Contrôle du cloisonnement : supabase/04_verifier_cloisonnement.sql
